### ISSUE TITLE
404 on FontAwesome file

### ISSUE THREAD

**Issue by bdw429s** [teamcfadvance/website#5]
When I load the site with my Chrome network tab open, the following URL shows a 404:

http://www.teamcfadvance.org/fonts/fontawesome-webfont.woff?v=4.2.0

**Comment by CreativeNotice** [comment]
Oh yes. Good catch. The server is missing the mime type for woff. I'll ping Denard about it when I get back to the house.

—

**Comment by ddspringle** [comment]
Added .woff (application/x-woff) mime type to the IIS server. Looks like it's working now. Let me know if you need anything else!

**Comment by CreativeNotice** [comment]
Thanks man!

—

**Comment by bdw429s** [comment]
Thanks guys!
